version: '3'

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775"   # UDP port for agent communication (bind to host's port 5775)
      - "6831:6831"   # UDP port for agent communication
      - "6832:6832"   # UDP port for agent communication
      - "5778:5778"   # HTTP port for health checks
      - "14250:14250" # gRPC port for OpenTelemetry
      - "14268:14268" # HTTP port for Jaeger collector API
      - "16686:16686" # Jaeger UI (web interface)
      - "14201:14201" # Jaeger query service (gRPC)
    networks:
      - jaeger-net

  jaeger-agent:
    image: jaegertracing/jaeger-agent
    container_name: jaeger-agent
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5776:5775"   # Change host port to 5776 (avoiding conflict)
    command:
      - --reporter.grpc.host-port=jaeger:14250
    networks:
      - jaeger-net

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

networks:
  jaeger-net:
    driver: bridge


#---------------------------------------------------------


