CREATE TABLE CUSTOMER_AADHAR_DATA_INFO(

   ID int(20) AUTO_INCREMENT PRIMARY KEY,
   AADHAR_NUMBER varchar (20) DEFAULT NULL,
   AADHAR_NAME varchar (40) DEFAULT NULL,
   RET VARCHAR (1) DEFAULT NULL,
   ENROLMENT_DATE VARCHAR (50) DEFAULT NULL,
   DOB VARCHAR (12) DEFAULT NULL,
   GENDER VARCHAR(1) DEFAULT NULL,
   CO VARCHAR (50) DEFAULT NULL,
   HOUSE VARCHAR (50) DEFAULT NULL,
   STREET  VARCHAR (50) DEFAULT NULL,
   LM  VARCHAR (50) DEFAULT NULL,
   LOC  VARCHAR (50) DEFAULT NULL,
   VTC VARCHAR (50) DEFAULT NULL,
   DIST VARCHAR (50) DEFAULT NULL,
   STATE  VARCHAR (50) DEFAULT NULL,
   PINCODE VARCHAR (10) DEFAULT NULL,
   POST_OFFICE  VARCHAR (50) DEFAULT NULL,
   PHOTO LONGBLOB,
   AADHAR_PDF LONGBLOB
);