CREATE TABLE AADHAR_MOBILE_LINKAGE_INFO(

   ID int(20) AUTO_INCREMENT PRIMARY KEY,
   AADHAR_NUMBER varchar (20) DEFAULT NULL,
   MOBILE_NUMBER varchar (15) DEFAULT NULL,
   AADHAR_MOBILE_LINKAGE_VALUE char(1) DEFAULT NULL

);

