CREATE TABLE PAN_AADHAR_LINKAGE_INFO(

    ID int(20) AUTO_INCREMENT PRIMARY KEY,
  PAN_NUMBER varchar (10) DEFAULT NULL,
  AADHAR_NUMBER varchar (20) DEFAULT NULL,
  PAN_AADHAR_LINKAGE_VALUE char(1) DEFAULT NULL

);

