CREATE TABLE POSIDEX_CUSTOMER_AADHAR_REF (
    AADHAR_REF_NO VARCHAR(15) PRIMARY KEY

);

CREATE TABLE POSIDEX_CUSTOMER_DETAILS_TABLE (
	AADHAR_REF_NO VARCHAR(255),
    SOURCE_SYSTEM VARCHAR(255),
    SCHEME_ID VARCHAR(255),
    LOCAL_APPLICATION_NO VARCHAR(255),
    BUSINESS_UNIT VARCHAR(255),
	SYSTEM_STATUS VARCHAR(50),
    BUSINESS_TYPE VARCHAR(255),
	TYPE_OF_APPLICANT VARCHAR(255),
	CUSTOMER_IDENTIFIER VARCHAR(255),
	CUSTOMER_CATEGORY VARCHAR(255),
	CRN BIGINT  AUTO_INCREMENT PRIMARY KEY,
	ACCOUNT_NO VARCHAR (255),
	EMAIL_ID VARCHAR(255),
	MOBILE_NUMBER VARCHAR(255),
	VOTER_ID VARCHAR(255),
    PASSPORT_NO VARCHAR(255),
    PAN VARCHAR(255),
    NAME VARCHAR(255),
    GENDER VARCHAR(255),
    DOB VARCHAR(50),
    MOTHER_NAME VARCHAR(255),
    FATHER_NAME VARCHAR(255),
    SPOUSE_NAME VARCHAR(255),
	ADDRESS_TYPE VARCHAR(50),
	STATE_NAME VARCHAR(50),
    PINCODE VARCHAR(20),
    CITY VARCHAR(255),
    ADDRESS VARCHAR(255),
     FK_AADHAR_REF_NO VARCHAR(15),
    FOREIGN KEY (FK_AADHAR_REF_NO) REFERENCES POSIDEX_CUSTOMER_AADHAR_REF (AADHAR_REF_NO)

)  AUTO_INCREMENT = 10000000001;


